language: rust
cache: cargo

rust:
  - stable

os:
  - linux

dist:
  - xenial

GITHUB_TOKEN: &GITHUB_TOKEN
  secure: vctr4gmX+NLl4aQsZt2IqcQOHhLEs/sedX6uw+E7Jh7YD5lCG2dSNDeb3kiVQoDJ8QK9AJZm2TtxbzmVTwe3aDpnyLipYrVztvwbUtG0mXXk9wjbLGjCWSek9Uw9yZp87dYIQzsnxSu7fHJqz76LkdKhp7eA5NENSH9Qhr9xs8D97SBFDBaDj41w3RlOewH/AQdm+XtEM3xrocy88dudXcIlzByxVX9eNGoUOPZJDFvK+V9YXLVVpru7RHvnjS0NozEPQeGmwHrHLSbzI79Q/s8VBupvUUEvuM7GP1z2zcZRznGF0njvotqoIlPL/fJnvt6vqMTKhUOUTVNKoQ1kLfhALNi7j+MW/eOF4mO6TBvU/dSeXs0LCdThqbXtmxm8ch7KMdKUWXOzw4PtTdqADvlkLLbyIuRtUOA3rNUO1K76m6UGVPdYWF7dpQb6Gkps9rTt+ZACDnhkmFAYUei99hfSSk36nB790XOGnoTDj+R8A3GGmyaO808imCnh3BNuCIiYEUH0Z5qPhYzdeUp4HSsE4KsQLnQUUHc3yP30HOSn2wDnzKVKlhTFFUVqMe0Kj/+6mrgEQbMnvM9qV7GjtqQffX3ZFNyjsmUCPd71eJegl9oUlCjygIybSxby+/TBQAEhRvr855b0Y4wGChfb12Ev+H4egJfyjooCjwYlhEQ=

script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all

#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "bmilanov"
#  - git config --local user.email "bmilanov11@gmail.com"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token: *GITHUB_TOKEN
  file: target/release/timeledger
  skip_cleanup: true
  on:
    repo: bmilanov/timeledger
    branch: master
    tags: true
